# Site settings
title: Ren'Py Tutorial
description: Ren'Py：从入门到入坟
baseurl: "/RenPy-Tutorial/doc" # the subpath of your site, e.g. /blog
url: "https://zyksslm.github.io" # the base hostname & protocol for your site

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Syntax highlighting
highlighter: rouge
kramdown:
  syntax_highlighter: rouge