site_name: Ren'Py：从入门到入坟
site_url: https://ZYKsslm.github.io/RenPy-Tutorial
repo_url: https://github.com/ZYKsslm/RenPy-Tutorial

theme:
  name: material
  language: zh
  
  icon:
    logo: material/book-open-page-variant
    repo: fontawesome/brands/github
      
  features:
    - content.code.copy
    - navigation.tracking

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue  # 浅色模式主色调
      accent: purple  # 浅色模式强调色
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式
        
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo  # 深色模式主色调
      accent: pink  # 深色模式强调色
      toggle:
        icon: material/brightness-4
        name: 切换到浅色模式

markdown_extensions:
  - pymdownx.tilde
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}

nav:
  - 在开始之前: 在开始之前.md
  - 你好，Ren'Py。: 你好，Ren'Py。.md
  - 变量: 变量.md
  - 脚本标签: 脚本标签.md
  - 对话: 对话.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ZYKsslm
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/590816142

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/prism.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/components/prism-renpy.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/components/prism-python.min.js

extra_css:
  - https://cdn.jsdelivr.net/npm/prism-themes/themes/prism-one-dark.css
  